askdjango/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.conf.urls.static import static
from django.conf import settings
from django.shortcuts import redirect
from django.views.generic import RedirectView


urlpatterns = [
    # 최상위 주소 들어오며면 이동경로
    url(r'^$', lambda r: redirect('blog:post_list'), name='root'),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('accounts.urls')),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^shop/', include('shop.urls', namespace='shop')),
    url(r'^blog/', include('blog.urls', namespace='blog')),
    url(r'^dojo/', include('dojo.urls', namespace='dojo')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar
    urlpatterns += [
        url(r'^__debug__/', include(debug_toolbar.urls)),
    ]

blog/urls.py
# blog/urls.py
from django.conf.urls import url
from . import views
from . import views_cbv


urlpatterns = [
    # 최상위 주소 설정, 함수 () 형태가 아닌 함수 자체 호출
    url(r'^$', views_cbv.post_list, name='post_list'),
    url(r'^(?P<pk>\d+)/$', views_cbv.post_detail, name='post_detail'),

    url(r'^new/$', views.post_new, name='post_new'),
    url(r'^(?P<id>\d+)/edit/$', views.post_edit, name='post_edit'),

    url(r'^comments/$', views.comment_list, name='comment_list'),

    url(r'^cbv/new/$', views_cbv.post_new),
    url(r'^cbv/(?P<pk>\d+)/edit/$', views_cbv.post_edit),
    url(r'^cbv/(?P<pk>\d+)/delete/$', views_cbv.post_delete),
]

blog/models.py
# blog/models.py
import re
from django.forms import ValidationError
from django.conf import settings
from django.db import models
from django.core.urlresolvers import reverse
# from imagekit.models import ImageSpecField
# from imagekit.processors import Thumbnail


def lnglat_validator(value):
    if not re.match(r'^([+-]?\d+\.?\d*),([+-]?\d+\.?\d*)$', value):
        raise ValidationError('Invalid LngLat Type')  # 예외 발생


class Post(models.Model):
    STATUS_CHOICES = (
        ('d', 'Draft'),
        ('p', 'Published'),
        ('w', 'Withdrawn'),
    )

    # author = models.CharField(max_length=20)
    user = models.ForeignKey(settings.AUTH_USER_MODEL)
    title = models.CharField(max_length=100, verbose_name='제목',
        help_text='포스팅 제목을 입력해주세요. 최대 100자 내외.')  # 길이 제한이 있는 문자열
    # choices = (
    #     ('제목1', '제목1 레이블'),  # 저장될 값, UI에 보여질 레이블
    #     ('제목2', '제목2 레이블'),
    #     ('제목3', '제목3 레이블'),
    # )
    content = models.TextField(verbose_name='내용')  # 길이 제한이 없는 문자열
    photo = models.ImageField(blank=True, upload_to='blog/post/%Y/%m/%d')
    # post_detail.html에서 직접 처리해줌
    # photo_thumbnail = ImageSpecField(source='photo',
    #         processors=[Thumbnail(300, 300)],
    #         format='JPEG',
    #         options={'quality': 60})
    tags = models.CharField(max_length=100, blank=True)
    lnglat = models.CharField(max_length=50,
        validators=[lnglat_validator],  # 함수 호출이 아닌 함수 자체 넘김
        blank=True, help_text='위도/경도 포맷으로 입력')
    status = models.CharField(max_length=1, choices=STATUS_CHOICES)
    tag_set = models.ManyToManyField('Tag', blank=True) # 문자열로 지정 가능(현재 Tag 클래스가 더 밑에 있기 때문), 블랭크 옵션은 필수 항목인지 아닌지
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ['id']

    def __str__(self):
        return self.title

# Create, Update가 성공시 넘어가는 url
    def get_absolute_url(self):
        return reverse('blog:post_detail', args={self.id})


class Comment(models.Model):
    post = models.ForeignKey(Post)
    author = models.CharField(max_length=20)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)


class Tag(models.Model):
    name = models.CharField(max_length=50, unique=True)

blog/forms.py
from django import forms
from .models import Post
from askdjango.widgets.naver_map_point_widget import NaverMapPointWidget

class PostForm(forms.ModelForm):
    # dummy = forms.CharField(widget=NaverMapPointWidget(attrs={'width': "100%", 'height': 200}))

    class Meta:
        model = Post
        fields = '__all__'
        widgets = {
            'lnglat': NaverMapPointWidget(attrs={'width': 600, 'height': 300}),
        }

blog/views.py
# blog/views.py
from django.contrib import messages
from django.http import Http404
from django.shortcuts import render, get_object_or_404, redirect
from .models import Post, Comment
from .forms import PostForm



def post_list(request):
    # print(request.user)

    qs = Post.objects.all().prefetch_related('tag_set', 'comment_set')

    q = request.GET.get('q', '')
    if q:
        qs = qs.filter(title__contains=q)

    return render(request, 'blog/post_list.html', {
        'post_list': qs,
        'q': q,
    })


def post_detail(request, id):
    # try:
    #     post = Post.objects.get(id=id)
    # except Post.DoesNotExist:
    #     raise Http404

    post = get_object_or_404(Post, id=id)
    return render(request, 'blog/post_detail.html', {
        'post': post,
    })


def post_new(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save()
            messages.success(request, '새 포스팅을 저장했습니다.')
            return redirect(post) # post.get_absolute_url() => post detail
    else:
        form = PostForm()
    return render(request, 'blog/post_form.html', {
        'form': form
    })


def post_edit(request, id):
    post = get_object_or_404(Post, id=id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save()
            messages.success(request, '포스팅을 수정했습니다.')
            return redirect(post) # post.get_absolute_url() => post detail
    else:
        form = PostForm(instance=post)
    return render(request, 'blog/post_form.html', {
        'form': form
    })


def comment_list(requset):
    comment_list = Comment.objects.all().select_related('post') # 뒤에 셀렉트 붙여 쿼리 개수 줄임
    return render(requset, 'blog/comment_list.html', {
        'comment_list': comment_list,
    })

blog/templates/blog/comment_list.html
{% extends "blog/layout.html" %}

{% block content %}

    <ul>
    {% for comment in comment_list %}
    <li>
        {{ comment }}
        {{ comment.post }}
    </li>

    {% endfor %}
    </ul>

{% endblock %}

blog/templates/blog/layout.html
{% extends "layout.html" %}

{% block title %}AskDjango's Blog{% endblock %}

blog/templates/blog/post_confirm_delete.html
<h1>{{ post }} 삭제확인</h1>

정말 삭제하시겠습니까?

<form action="" method="post">
    {% csrf_token %}
    <a href="{{ post.get_absolute_url }}">아니요. 취소!</a>
    <input type="submit" value="예. 삭제하겠습니다." />
</form>

blog/templates/blog/post_detail.html
{% extends "blog/layout.html" %}
{% load imagekit %}

{% block title %}
    {{ post.title }}
{% endblock %}

{% block content %}
    <div class="container">
         <div class="row">
             <div class="col-sm-12">
                <h2>{{ post.title }}</h2>
                {% if post.photo %}
{#                    <img src="{{ post.photo.url }}" style="max-width: 100%" />#}
                    {% thumbnail "300x300" post.photo -- style="" onclick="" class="" %}
                {% endif %}

                <br>
                {{ post.content|linebreaksbr }}

                <hr/>

                <h3>Comments</h3>

                <ul>
                {% for comment in post.comment_set.all %}
                    <li>
                        {{ comment.message }}
                        <small>by {{ comment.author }}</small>
                        <small>at {{ comment.update_at }}</small>kk
                    </li>
                {% endfor %}
                </ul>

                <hr/>
                <a href="{% url "blog:post_list" %}" class="btn btn-primary">글 목록</a>
                <a href="{% url "blog:post_edit" post.id %}" class="btn btn-default">수정</a>
             </div>
         </div>
    </div>

{% endblock %}

blog/templates/blog/post_form.html
<!-- blog/templates/blog/post_form.html -->

<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" />
</form>

blog/templates/blog/post_list.html
{% extends "blog/layout.html" %}

{% block content %}
    <div class="container">
        <div class="jumbotron">
            <h1>Django Template <sup>by AskDjango</sup></h1>
            <p>여러분의 파이썬/장고 페이스메이커가 되겠습니다.</p>
            <p>
                <a class="btn btn-lg btn-primary" href="http://facebook.com/groups/askdjango">
                    AskDjango 페이스북 그룹 &raquo;
                </a>
            </p>
        </div>

        <div class="row">
            <div class="col-sm-12">
                <div class="alert alert-info">
                    <ul>
                    <li>http://localhost:8000/blog/ 주소로 접속해보세요.</li>
                    <li>템플릿 경로를 blog/templates/post_list.html 경로가 아닌 blog/</li>
                    <li>templates/blog/post_list.html 경로를 쓰는 지에 대한 이유는, 후에
                    Template Loader에서 설명합니다.</li>
                    </ul>
                </div>

                <a href="{% url "blog:post_new" %}" class="btn btn-primary pull-right">New Post</a>

                <p>
                <form action="" method="get">
                    <input type="text" name="q" value="{{ q }}" />
                    <input type="submit" value="검색" class="btn btn-primary" />
                </form>
                </p>
                <table class="table table-hover table-bordered">
                    <thead>
                        <tr>
                            <th>id</th>
                            <th>title</th>
                            <th>author</th>
                            <th>updated_at</th>
                        </tr>
                    </thead>
                    <tbody>
                        {% for post in post_list %}
                            <tr>
                                <td>{{ post.id }}</td>
                                <td>
                                    <a href="{% url "blog:post_detail" post.id %}">{{ post.title }}</a>
                                    {% for tag in post.tag_set.all %}
                                        <span class="label label-info">{{ tag.name }}</span>
                                    {% endfor %}
                                </td>
                                <td><small>by {{ post.author }}</small></td>
                                <td><small>at {{ post.updated_at }}</small></td>
{#                                <td>#}
{#                                    {{ post.comment_set.all }}#}
{#                                    {{ post.tag_set.all }}#}
{#                                </td>#}
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>

            </div>
        </div>


    </div>




{% endblock %}